### PR TITLE
Get Multiple Documents Endpoint through [GET] /documents

### PR DESCRIPTION
**Pull request by will-mcintyre**
Have added a function `get_documents` that is routed through the [GET] `\documents` endpoint.

Allows query parameters:
- page: requested page for sorted data
- limit: amount of documents loaded per page
- sort_order: display results sorted by default ascending document_id order or descending

Note that no associated accommodations are loaded in this request.

Example: 

`[GET] http://127.0.0.1:5000/documents?sort_order=desc&limit=10&page=1`

{
    "data": {
        "documents": [
            {
                "document_description": "This document is a newsletter providing information about various heat stress-mitigating products that are available for workers exposed to high temperatures. It describes different types of accommodations such as heat stress monitors, cooling helmets, hardhat attachments, face shield sunglasses, wearable cooling vests, evaporative cooling towels, and hydration vests. The newsletter emphasizes the importance of these products in preventing heat-related injuries and stresses the need for employers to implement safety guidelines and precautions in addition to using these products.",
                "document_id": 4,
                "document_name": "Accommodations - Heat Stress Products (WSIB Newsletter)",
                "extension": ".pdf",
                "url": "https://rtwblobwsib.blob.core.windows.net/rtwblobs/Accommodations%20-%20Heat%20Stress%20Products%20%28WSIB%20Newsletter%29"
            },
            {
                "document_description": "This document is a newsletter providing information about various heat stress-mitigating products that are available for workers exposed to high temperatures. It describes different types of accommodations such as heat stress monitors, cooling helmets, hardhat attachments, face shield sunglasses, wearable cooling vests, evaporative cooling towels, and hydration vests. The newsletter emphasizes the importance of these products in preventing heat-related injuries and stresses the need for employers to implement safety guidelines and precautions in addition to using these products.",
                "document_id": 5,
                "document_name": "Accommodations - Heat Stress Products (WSIB Newsletter)",
                "extension": ".pdf",
                "url": "https://rtwblobwsib.blob.core.windows.net/rtwblobs/Accommodations%20-%20Heat%20Stress%20Products%20%28WSIB%20Newsletter%29"
            },
            {
                "document_description": "This document discusses various accommodations to assist in controlling exposure to summer heat for workers. It lists several products like heat stress monitors, cooling helmets, hardhat attachments, face shield sunglasses, wearable cooling vests, evaporative cooling towels, cooling vests, and hydration vests. These products aim to prevent dehydration, heat exhaustion, and heatstroke, among other heat-related conditions. The document emphasizes that these devices should complement other precautions like regular breaks, training, and suitable work schedules in hot environments.",
                "document_id": 6,
                "document_name": "Accommodations - Heat Stress Products (WSIB Newsletter)",
                "extension": ".pdf",
                "url": "https://rtwblobwsib.blob.core.windows.net/rtwblobs/Accommodations%20-%20Heat%20Stress%20Products%20%28WSIB%20Newsletter%29"
            },
            {
                "document_description": "The document is an issue of the Accommodations News, focusing on equipment and tools used in the construction industry to prevent injuries and make tasks easier and safer. It introduces Drywall Panel Lifters, Manual Jacks, Door Lifters, Quick Cut Concrete Saw Carts, and Panel Carrier Tools, all aimed at minimizing the physical strain on workers.",
                "document_id": 7,
                "document_name": "Accommodations - Construction - Material Lifters (WSIB Newsletter) (2)",
                "extension": ".pdf",
                "url": "https://rtwblobwsib.blob.core.windows.net/rtwblobs/Accommodations%20-%20Construction%20-%20Material%20Lifters%20%28WSIB%20Newsletter%29%20%282%29"
            },
            {
                "document_description": "This document discusses the accommodations for bricklayers and stonemasons to reduce physical demands and the risk of injury. Some of the tools recommended include brick tongs, lifts on wheeled platforms, mortar silos, mortar stands, and adjustable scaffolding. These tools are designed to reduce lifting, bending, and the need for repeated adjustment of work heights. The document is part of the 'Construction Series' by the Accommodations SME’s and is featured in their volume 2/ issue 17 newsletter.",
                "document_id": 8,
                "document_name": "Accommodations - Construction - Bricklayer (WSIB Newsletter) (1)",
                "extension": ".pdf",
                "url": "https://rtwblobwsib.blob.core.windows.net/rtwblobs/Accommodations%20-%20Construction%20-%20Bricklayer%20%28WSIB%20Newsletter%29%20%281%29"
            },
            {
                "document_description": "The document is a newsletter focused on accommodations in the construction industry, particularly for bricklayers and stonemasons. It discusses the physical demands of the work and presents several tools and methods to reduce these demands and the risk of injury. These include brick tongs, a lift on a wheeled platform, mortar silos, mortar stands, and a scaffold with a hand lever.",
                "document_id": 12,
                "document_name": "Accommodations_-_Truck_Driver_-_Securing_the_Load_WSIB_Newsletter.pdf",
                "extension": "pdf",
                "url": "https://rtwblobwsib.blob.core.windows.net/rtwblobs/Accommodations_-_Truck_Driver_-_Securing_the_Load_WSIB_Newsletter.pdf"
            },
            {
                "document_description": "The document is a newsletter focused on accommodations in the construction industry, particularly for bricklayers and stonemasons. It discusses the physical demands of the work and presents several tools and methods to reduce these demands and the risk of injury. These include brick tongs, a lift on a wheeled platform, mortar silos, mortar stands, and a scaffold with a hand lever.",
                "document_id": 13,
                "document_name": "Accommodations_-_Retail_WSIB.docx",
                "extension": "docx",
                "url": "https://rtwblobwsib.blob.core.windows.net/rtwblobs/Accommodations_-_Retail_WSIB.docx"
            },
            {
                "document_description": "This document discusses various accommodations for bricklayers and stonemasons in the construction industry to reduce physical demands and risks of injury, detailing tools like brick tongs, mortar silos, mortar stands, and hand lever plank adjustment models.",
                "document_id": 14,
                "document_name": "Accommodations - Construction - Bricklayer (WSIB Newsletter)",
                "extension": "pdf",
                "url": "https://rtwblobwsib.blob.core.windows.net/rtwblobs/Accommodations%20-%20Construction%20-%20Bricklayer%20%28WSIB%20Newsletter%29"
            },
            {
                "document_description": "This document provides accommodation suggestions for the retail industry focusing on ergonomics to reduce risk factors causing work-related musculoskeletal disorders.",
                "document_id": 15,
                "document_name": "Accommodations - Retail (WSIB)",
                "extension": "docx",
                "url": "https://rtwblobwsib.blob.core.windows.net/rtwblobs/Accommodations%20-%20Retail%20%28WSIB%29"
            },
            {
                "document_description": "The document is a newsletter focused on accommodations in the construction industry, particularly for bricklayers and stonemasons. It discusses the physical demands of the work and presents several tools and methods to reduce these demands and the risk of injury. These include brick tongs, a lift on a wheeled platform, mortar silos, mortar stands, and a scaffold with a hand lever.",
                "document_id": 16,
                "document_name": "Accommodations_-_Construction_-_Material_Lifters_WSIB_Newsletter.pdf",
                "extension": "pdf",
                "url": "https://rtwblobwsib.blob.core.windows.net/rtwblobs/Accommodations_-_Construction_-_Material_Lifters_WSIB_Newsletter.pdf"
            },
            {
                "document_description": "The document is a newsletter focused on accommodations in the construction industry, particularly for bricklayers and stonemasons. It discusses the physical demands of the work and presents several tools and methods to reduce these demands and the risk of injury. These include brick tongs, a lift on a wheeled platform, mortar silos, mortar stands, and a scaffold with a hand lever.",
                "document_id": 17,
                "document_name": "Accommodations_-_Construction_-_Concrete_Screeding_Roller_NIOSH.pdf",
                "extension": "pdf",
                "url": "https://rtwblobwsib.blob.core.windows.net/rtwblobs/Accommodations_-_Construction_-_Concrete_Screeding_Roller_NIOSH.pdf"
            }
        ],
        "filters": {
            "sort_by": "document_id",
            "sort_order": "asc"
        },
        "pagination": {
            "has_next_page": false,
            "has_prev_page": false,
            "limit": 20,
            "page": 1,
            "total_items": 11,
            "total_pages": 1
        }
    },
    "message": "Documents retrieved successfully",
    "success": true
}

### CODE REVIEW

**Comment by sviatoslav0koval** [comment]
looks great, i like how clean the code is

**Comment by Varun-WSIB** [comment]
Looking good to me. Will test it a bit.

**Comment by Varun-WSIB** [comment]
There are more links than documents including repeat docs.

**Review by Varun-WSIB — APPROVED** [review]
The code works.

**Pull request merged**
